<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="MonadicSharp" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Klexir.Engine.Abstractions\Klexir.Engine.Abstractions.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Klexir.Engine.Tests" />
  </ItemGroup>
</Project>
